### ISSUE TITLE
Not getting contacts in IOS device

### ISSUE THREAD

**Issue by farrukh-hashmi** [lucbelliveau/react-native-simple-contacts#2]
findContactByNumber not getting contact. Already test it with android and it is working fine in android but not getting contact in IOS device. Manual settings are verified. Getting 1 in response

**Comment by U-day** [comment]
I too get 1 in response on IOS. Would really appreciate a fix. Thank you.

**Comment by lucbelliveau** [comment]
only contacts with a "mobile" number were being returned, now all users will be returned... with number=mobile when possible, and the first available otherwise.

**Comment by U-day** [comment]
Testing in IOS 6s Plus simulator **getContacts()** returns all the contacts with mobile or phone.
Testing in iPhone 5s with over 1600 contacts, **getContacts()** returns ONE contact who does not have a phone number.
Still, both in the IOS simulator and iPhone, **getProfile()** and **findContactByNumber(number)** return the number 1.

**Comment by U-day** [comment]
Dear Luc,

Testing in IOS 6s Plus simulator getContacts() returns all the contacts with mobile or phone.
Testing in iPhone 5s with over 1600 contacts, getContacts() returns ONE contact who does not have a phone number.
Still, both in the IOS simulator and iPhone, getProfile() and findContactByNumber(number) return the number 1. 

Would really appreciate a solution for this problem.

Thanks,

Uday
